pipeline {
    agent any

    tools {
        jdk 'JDK21'
        maven 'Maven'
    }

    environment {
        DEPLOY_DIR  = 'C:\\deploy'
        APP_NAME    = 'employee-management-app.jar'
        APP_PORT    = '8085'
        BUILD_VER   = "1.0.${BUILD_NUMBER}"
    }

    stages {

        stage('Clone Code') {
             steps {
                git branch: 'employee-management-app',
                    credentialsId: 'github-ssh',
                    url: 'git@github.com:bhagwan-raut/master.git'
            }
        }

       stage('Set Version') {
            steps {
                dir('employee-management-app') {
                    bat "mvn versions:set -DnewVersion=${BUILD_VER}"
                }
            }
        }

        stage('Build JAR') {
            steps {
                bat 'mvn clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }

        stage('Stop Old App') {
            steps {
                bat '''
                    for /f "tokens=5" %%a in ('netstat -aon ^| findstr ":8085"') do (
                        taskkill /PID %%a /F 2>nul
                    )
                    exit 0
                '''
            }
        }

        stage('Deploy JAR') {
            steps {
                bat 'if not exist %DEPLOY_DIR% mkdir %DEPLOY_DIR%'
                bat 'copy /Y target\\*.jar %DEPLOY_DIR%\\%APP_NAME%'
            }
        }

        stage('Start App') {
            steps {
                bat 'start /B java -jar %DEPLOY_DIR%\\%APP_NAME% > %DEPLOY_DIR%\\app.log 2>&1'
                echo "App version ${BUILD_VER} started at http://localhost:8085"
            }
        }

        stage('Tag Build on GitHub') {
            steps {
                bat "git tag -a v${BUILD_VER} -m \"Jenkins Build ${BUILD_VER}\""
                bat "git push https://YOUR_TOKEN@github.com/bhagwan-raut/master.git v${BUILD_VER}"
            }
        }

       stage('Commit Build Number') {
        steps {
        sshagent(['github-ssh']) {
            bat "git config user.email \"bhagwanraut0597@gmail.com\""
            bat "git config user.name \"bhagwan-raut\""
            bat "echo ${BUILD_VER} > build-version.txt"
            bat "git add build-version.txt"
            bat "git commit -m \"Jenkins Auto Build - Version ${BUILD_VER} [skip ci]\""
            bat "git push git@github.com:bhagwan-raut/master.git HEAD:employee-management-app"
                }
            }
        }
     }

    post {
        success {
            echo "✅ Build ${BUILD_VER} Successful!"
            echo "Access at: http://localhost:8085/api/employees"
        }
        failure {
            echo "❌ Build ${BUILD_VER} Failed!"
        }
    }
}
